CREATE TABLE [dbo].[Clients]
(
	 [Id]					INT				NOT NULL IDENTITY(1,1)
	,[Name]					NVARCHAR(200)	NOT NULL
	,[DateCreatedUtc]		DATETIMEOFFSET	NOT NULL DEFAULT GETUTCDATE(), 
	,[DateLastUpdatedUtc]	DATETIMEOFFSET	NOT NULL DEFAULT GETUTCDATE(), 
    CONSTRAINT [PK_Clients] PRIMARY KEY ([Id])
)
